# Generated by Django 5.2.7 on 2025-11-05 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(max_length=20, unique=True)),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('tanggal_lahir', models.DateField()),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('jurusan', models.CharField(max_length=100)),
                ('fakultas', models.CharField(max_length=100)),
                ('angkatan', models.PositiveIntegerField()),
                ('ipk', models.DecimalField(decimal_places=2, max_digits=3)),
                ('sks_lulus', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Aktif', 'Aktif'), ('Cuti', 'Cuti'), ('Lulus', 'Lulus'), ('Drop Out', 'Drop Out')], max_length=20)),
                ('alamat', models.TextField()),
                ('kota', models.CharField(max_length=100)),
                ('provinsi', models.CharField(max_length=100)),
                ('no_telepon', models.CharField(max_length=20)),
                ('nama_wali', models.CharField(max_length=100)),
                ('no_telepon_wali', models.CharField(max_length=20)),
            ],
        ),
    ]
